apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: flask-redirect-2
      app.kubernetes.io/component: flask-redirect-2
      app.kubernetes.io/instance: flask-redirect-2
    name: flask-redirect-2
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: flask-redirect-2
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: flask-redirect-2
      spec:
       containers:
        - image: 'quay.io/cpranava0/flask-redirect-2:main'
          name: flask-redirect-2
          ports:
          - containerPort: 5000
            protocol: TCP
          resources: {}
          env:
          - name: BASE_URL
            value: https://jsonplaceholder.typicode.com/todos/1 
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: flask-redirect-2
      app.kubernetes.io/component: flask-redirect-2
      app.kubernetes.io/instance: flask-redirect-2
    name: flask-redirect-2
  spec:
    ports:
    - name: 5000-tcp
      port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      deployment: flask-redirect-2
kind: List
metadata: {}

